### PR TITLE
Added style theme - old mix

### PR DESCRIPTION
**Pull request by MrMarvel**

### CODE REVIEW

**Comment by cloudcloudskies** [comment]
the font must be changed to arial bold for accuracy also why did you changed the script?

**Comment by MrMarvel** [comment]
@cloudskies13 ,
> the font must be changed to arial bold for accuracy ...

I tried to copy style of terminal from this video: https://youtu.be/lT-NxwrjgZM.
It wasn't look as arial. I used OCR A for more sharp edges btw I think it looks cooler. I understand that's not original game font.
> ... why did you changed the script

I didn't touch code logic. I refactored CR endings -> LF endings in repo. I assume original author was working on windows and having autocrlf=false.
```bash
F:\TEMP\wantyougone [main ↓1]> git ls-files --eol . | grep i/cr
i/crlf  w/crlf  attr/                   WYGgen.py
i/crlf  w/crlf  attr/                   lyrics.txt
i/crlf  w/crlf  attr/                   requirements.txt
i/crlf  w/crlf  attr/                   start.py
F:\TEMP\wantyougone [main ↓1]>
```

**Comment by MrMarvel** [comment]
But probably I need to separate crlf and styles in 2 pulls. Is there sense to do it?

**Comment by create-juicey-app** [comment]
i also used OCR A for the vid, gonna check the request then maybe pull it

**Comment by cloudcloudskies** [comment]
in portal 2, arial bold was used

**Comment by MrMarvel** [comment]
Created pull with only styles without any files or git refactoring.
https://github.com/create-juicey-app/wantyougone/pull/6

**Pull request closed without merging**
