### PR TITLE
Added color via ANSI escape codes

### PR DESCRIPTION
**Pull request by ToyB-Chan**
This PR adds the fitting foreground and background colors via [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code). I also replaced the OS dependent clear function with the ANSI equivalent while I was at it. This currently breaks the GUI mode, but as the GUI mode only seems to circumvent the color issue I wonder if its worth to keep it up anyway. I can fix that if necessary tho.

### CODE REVIEW

**Comment by cloudcloudskies** [comment]
hmm can i add this to my pr? it optimizes things and adds new things

**Comment by create-juicey-app** [comment]
ANSI escape codes may be useful, but i may be afraid this change might break other scripts like the gui version.

**Comment by ToyB-Chan** [comment]
> hmm can i add this to my pr? it optimizes things and adds new things

I don't really see a reason here to not keep the PRs seperate tbh. Also sorry for the late reply.

**Comment by ToyB-Chan** [comment]
> ANSI escape codes may be useful, but i may be afraid this change might break other scripts like the gui version.

Yeah like I said, it breaks the gui version (gui just prints the escape codes and clear doesn't work), but that's fixable if you're planning to keep the gui version around.

**Comment by cloudcloudskies** [comment]
hmm thanks for access

**Comment by create-juicey-app** [comment]
i do want the gui version still here, and i wish one day i'll have the motivation to bring it to pygame and not tkinter

**Comment by create-juicey-app** [comment]
Breaks the gui, will rewrite the gui version in a later time

**Pull request closed without merging**
